<?php

/**
 * @file
 * Dam Gates status content type customizations.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\srdgs_custom\Hook\SrdgsCustomHooks;

/**
 * Implements hook_form_FORM_ID_alter().
 */
#[LegacyHook]
function srdgs_custom_form_node_dam_gates_status_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(SrdgsCustomHooks::class)->formNodeDamGatesStatusFormAlter($form, $form_state, $form_id);
}
